# Site settings
title: Maine Chi Alpha
email: umainechialpha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Need description from Chels
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://mainechialpha.com" # the base hostname & protocol for your site
url: "https://mainechialpha.github.io" # the base hostname & protocol for your site
facebook_username: chialphaumaine
instagram_username: 

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
excerpt_separator: <!--endexcerpt-->
