# Site settings
title: MAINE CHI ALPHA
email: umainechialpha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Need description from Chels
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://mainechialpha.com" # the base hostname & protocol for your site
url: "https://mainechialpha.github.io" # the base hostname & protocol for your site
facebook_url: https://www.facebook.com/chialphaumaine/
instagram_url: https://www.instagram.com/umainexa/ 

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
excerpt_separator: <!--endexcerpt-->
